# Generated by Django 5.2 on 2025-05-09 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'es').", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Language name (e.g., 'English', 'Spanish').", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is active for use in templates.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Concise title for the case.', max_length=255)),
                ('subspecialty', models.CharField(choices=[('neuro', 'Neuroradiology'), ('msk', 'Musculoskeletal'), ('body', 'Body Imaging'), ('peds', 'Pediatric Radiology'), ('breast', 'Breast Imaging'), ('ir', 'Interventional Radiology'), ('nucmed', 'Nuclear Medicine'), ('other', 'Other')], default='peds', help_text='Primary subspecialty category.', max_length=50)),
                ('modality', models.CharField(choices=[('CT', 'Computed Tomography'), ('MRI', 'Magnetic Resonance Imaging'), ('XR', 'X-Ray (Radiography)'), ('US', 'Ultrasound'), ('fluoro', 'Fluoroscopy'), ('PET', 'Positron Emission Tomography'), ('mammo', 'Mammography'), ('other', 'Other')], help_text='Primary imaging modality used.', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Estimated difficulty level.', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the case.', max_length=20)),
                ('patient_age', models.PositiveIntegerField(blank=True, help_text='Patient age at the time of imaging (in years, optional).', null=True)),
                ('clinical_history', models.TextField(help_text='Brief clinical history presented to the radiologist.')),
                ('key_findings', models.TextField(help_text='Description of the key imaging findings (expert).')),
                ('diagnosis', models.CharField(help_text='Final diagnosis or differential diagnoses.', max_length=500)),
                ('discussion', models.TextField(help_text='Detailed discussion of the case, findings, diagnosis, and teaching points.')),
                ('references', models.TextField(blank=True, help_text='Optional references or further reading (e.g., PubMed links, articles).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when the case was first published.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='The case this template instance belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='applied_templates', to='cases.case')),
                ('language', models.ForeignKey(help_text='The language this specific instance of the template is for.', on_delete=django.db.models.deletion.PROTECT, related_name='case_specific_templates', to='cases.language')),
            ],
            options={
                'unique_together': {('case', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MasterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for this master template, e.g., 'Non-contrast Brain MRI - Standard'", max_length=255, unique=True)),
                ('modality', models.CharField(blank=True, choices=[('CT', 'Computed Tomography'), ('MRI', 'Magnetic Resonance Imaging'), ('XR', 'X-Ray (Radiography)'), ('US', 'Ultrasound'), ('fluoro', 'Fluoroscopy'), ('PET', 'Positron Emission Tomography'), ('mammo', 'Mammography'), ('other', 'Other')], help_text='Primary imaging modality this template is designed for, if any.', max_length=50, null=True)),
                ('body_part', models.CharField(blank=True, choices=[('brain', 'Brain'), ('head-neck', 'Head & Neck'), ('chest', 'Chest'), ('abdomen', 'Abdomen'), ('pelvis', 'Pelvis'), ('spine', 'Spine'), ('msk', 'Musculoskeletal'), ('other', 'Other')], help_text='Primary body part this template is designed for, if any.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for admin reference.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this master template available for use?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_master_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='master_template',
            field=models.ForeignKey(blank=True, help_text='The master report template selected for this case, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_cases', to='cases.mastertemplate'),
        ),
        migrations.CreateModel(
            name='MasterTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Section name (e.g., 'Clinical History', 'Findings', 'Impression').", max_length=100)),
                ('placeholder_text', models.TextField(blank=True, help_text='Default placeholder text or instructions for this section.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this section appears in the template.')),
                ('is_required', models.BooleanField(default=True)),
                ('master_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cases.mastertemplate')),
            ],
            options={
                'ordering': ['master_template', 'order'],
                'unique_together': {('master_template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserCaseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'case')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have viewed this case.', related_name='viewed_cases', through='cases.UserCaseView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CaseTemplateSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The actual template text for this section, for this specific case and language.')),
                ('case_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_contents', to='cases.casetemplate')),
                ('master_section', models.ForeignKey(help_text='The master section this content is for.', on_delete=django.db.models.deletion.CASCADE, related_name='case_specific_contents', to='cases.mastertemplatesection')),
            ],
            options={
                'unique_together': {('case_template', 'master_section')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(help_text="User's description of the imaging findings.")),
                ('impression', models.TextField(help_text="User's impression, diagnosis, or differential diagnoses.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'case')},
            },
        ),
    ]
