# Generated by Django 5.2 on 2025-05-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_casetemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='report',
            name='impression',
        ),
        migrations.AddField(
            model_name='report',
            name='structured_content',
            field=models.JSONField(blank=True, default=list, help_text="Stores the user's report content, structured by master template sections."),
        ),
    ]
