# Generated by Django 5.2 on 2025-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_report_findings_remove_report_impression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='orthanc_study_uid',
            field=models.CharField(blank=True, help_text='The DICOM StudyInstanceUID for the primary study in Orthanc associated with this case.', max_length=255, null=True),
        ),
    ]
