# Generated by Django 5.2 on 2025-05-17 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_orthanc_study_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_identifier',
            field=models.CharField(blank=True, help_text='Human-readable unique ID (e.g., NR-MR-2025-0001). Auto-generated if left blank.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='patient_sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], help_text="Patient's biological sex if relevant and known", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='casetemplatesectioncontent',
            name='key_concepts_text',
            field=models.TextField(blank=True, help_text='Admin-defined, case-specific key concepts for this section of this expert template (semicolon-separated phrases).', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True, help_text="Expert's final diagnosis for THIS CASE.", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='discussion',
            field=models.TextField(blank=True, help_text="Expert's discussion points for THIS CASE.", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='key_findings',
            field=models.TextField(blank=True, help_text="Expert's key imaging findings summary for THIS CASE (semicolon-separated phrases recommended for AI use).", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='references',
            field=models.TextField(blank=True, help_text='References or further reading (URLs/citations, one per line).', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(help_text='Internal title for admin organization.', max_length=255),
        ),
        migrations.CreateModel(
            name='AIFeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text="User's star rating for the AI feedback (1-5).")),
                ('comment', models.TextField(blank=True, help_text='Optional textual comment from the user about the AI feedback.', null=True)),
                ('rated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the rating was submitted.')),
                ('report', models.ForeignKey(help_text='The user report for which AI feedback was provided and is being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_ratings', to='cases.report')),
                ('user', models.ForeignKey(help_text='The user who is providing the rating for the AI feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback Rating',
                'verbose_name_plural': 'AI Feedback Ratings',
                'ordering': ['-rated_at'],
                'unique_together': {('report', 'user')},
            },
        ),
    ]
