# Generated by Django 5.2 on 2025-05-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_case_identifier_case_patient_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_feedback_content',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the AI-generated feedback content for this report.'),
        ),
    ]
