# Generated by Django 5.2 on 2025-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_report_ai_feedback_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Flag to mark this report as archived. Archived reports are kept for history but not shown as the current report.'),
        ),
    ]
