# Generated by Django 5.2 on 2025-10-12 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_report_unique_together_report_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier (UUID).', primary_key=True, serialize=False)),
                ('turns_count', models.IntegerField(default=0, help_text='Current number of conversation turns in this session.')),
                ('max_turns', models.IntegerField(default=10, help_text='Maximum allowed turns for this session.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', help_text='Current status of the tutoring session.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created.')),
                ('last_turn_at', models.DateTimeField(auto_now=True, help_text='When the last turn was created in this session.')),
                ('report', models.ForeignKey(help_text='The user report this tutoring session is about.', on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='cases.report')),
                ('user', models.ForeignKey(help_text='The user engaging in this tutoring session.', on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutoring Session',
                'verbose_name_plural': 'Tutoring Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutoringTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(help_text='Sequential turn number within this session (1, 2, 3, ...).')),
                ('user_message', models.TextField(help_text="The user's question or message in this turn.")),
                ('ai_response', models.TextField(help_text="The AI tutor's response to the user's message.")),
                ('tools_used', models.JSONField(blank=True, default=list, help_text="List of tool names used to generate this response (e.g., ['fetch_image', 'vlm_analysis']).")),
                ('image_references', models.JSONField(blank=True, default=list, help_text="List of image references detected in user message (e.g., [{'series': 5, 'image': 35}]).")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this turn was created.')),
                ('response_time_ms', models.IntegerField(help_text='Time taken to generate AI response in milliseconds.')),
                ('session', models.ForeignKey(help_text='The tutoring session this turn belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='cases.tutoringsession')),
            ],
            options={
                'verbose_name': 'Tutoring Turn',
                'verbose_name_plural': 'Tutoring Turns',
                'ordering': ['turn_number'],
            },
        ),
        migrations.AddIndex(
            model_name='tutoringsession',
            index=models.Index(fields=['report'], name='tutoring_report_idx'),
        ),
        migrations.AddIndex(
            model_name='tutoringsession',
            index=models.Index(fields=['user', 'created_at'], name='tutoring_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tutoringsession',
            index=models.Index(fields=['status'], name='tutoring_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tutoringsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('report', 'user'), name='unique_active_session_per_report_user'),
        ),
        migrations.AddIndex(
            model_name='tutoringturn',
            index=models.Index(fields=['session', 'turn_number'], name='tutoring_turn_session_num_idx'),
        ),
        migrations.AddIndex(
            model_name='tutoringturn',
            index=models.Index(fields=['created_at'], name='tutoring_turn_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tutoringturn',
            unique_together={('session', 'turn_number')},
        ),
    ]
