# Generated by Django 5.2 on 2025-10-13 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_tutoring_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique version identifier (UUID).', primary_key=True, serialize=False)),
                ('version_number', models.CharField(help_text="Semantic version (e.g., 'v1.2.3', 'v2.0.0').", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Improved Specificity v2').", max_length=200)),
                ('description', models.TextField(help_text='What changed in this version and why (changelog entry).')),
                ('prompt_template', models.TextField(help_text='Full prompt template with placeholders for context variables.')),
                ('is_active', models.BooleanField(default=False, help_text='Is this version currently in use? (only one can be true)')),
                ('is_ab_test', models.BooleanField(default=False, help_text='Is this version part of an A/B test?')),
                ('ab_test_weight', models.IntegerField(default=0, help_text='Weight for A/B testing (0-100, higher = more traffic). Total weights should sum to 100.')),
                ('total_uses', models.IntegerField(default=0, help_text='Number of times this prompt was used to generate feedback.')),
                ('average_rating', models.FloatField(blank=True, help_text='Average overall rating for feedback from this prompt (calculated from ratings).', null=True)),
                ('average_accuracy', models.FloatField(blank=True, help_text='Average accuracy rating for this prompt version.', null=True)),
                ('average_helpfulness', models.FloatField(blank=True, help_text='Average helpfulness rating for this prompt version.', null=True)),
                ('average_actionability', models.FloatField(blank=True, help_text='Average actionability rating for this prompt version.', null=True)),
                ('total_tokens_used', models.BigIntegerField(default=0, help_text='Total tokens consumed by this prompt version.')),
                ('average_tokens_per_use', models.FloatField(blank=True, help_text='Average tokens per feedback generation (for cost estimation).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created.')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this version was first activated.', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When this version was deactivated.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this prompt version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Version',
                'verbose_name_plural': 'Prompt Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique cache entry identifier (UUID).', primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 hash of normalized report content (user + expert + case context).', max_length=64, unique=True)),
                ('feedback_content', models.JSONField(help_text='Cached AI feedback response (structured JSON format).')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cache entry was served.')),
                ('last_hit_at', models.DateTimeField(blank=True, help_text='Last time this cache was hit.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this cache entry was created.')),
                ('expires_at', models.DateTimeField(help_text='Cache expiration timestamp (invalidate after prompt changes).')),
                ('case', models.ForeignKey(help_text='Case for which feedback was generated (for analytics).', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_caches', to='cases.case')),
                ('prompt_version', models.ForeignKey(blank=True, help_text='Prompt version used to generate this cached feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_feedbacks', to='cases.promptversion')),
            ],
            options={
                'verbose_name': 'Feedback Cache Entry',
                'verbose_name_plural': 'Feedback Cache Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique log entry identifier (UUID).', primary_key=True, serialize=False)),
                ('input_tokens', models.IntegerField(help_text='Tokens in prompt (input to LLM).')),
                ('output_tokens', models.IntegerField(help_text='Tokens in response (output from LLM).')),
                ('total_tokens', models.IntegerField(help_text='input_tokens + output_tokens.')),
                ('input_cost', models.DecimalField(decimal_places=6, help_text='Cost for input tokens in USD (based on model pricing).', max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=6, help_text='Cost for output tokens in USD (based on model pricing).', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, help_text='Total cost for this request in USD.', max_digits=10)),
                ('response_time_ms', models.IntegerField(help_text='Time to receive response in milliseconds (for monitoring).')),
                ('was_cached', models.BooleanField(default=False, help_text='Was this served from cache? (if true, tokens/costs are 0)')),
                ('model_name', models.CharField(help_text="AI model used (e.g., 'gemini-2.5-flash', 'gemini-1.5-flash').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this request was made.')),
                ('case', models.ForeignKey(help_text='Case associated with this request (for cost per case analytics).', on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to='cases.case')),
                ('prompt_version', models.ForeignKey(blank=True, help_text='Prompt version used for this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage_logs', to='cases.promptversion')),
                ('report', models.ForeignKey(help_text='Report for which feedback was generated.', on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_logs', to='cases.report')),
            ],
            options={
                'verbose_name': 'Token Usage Log',
                'verbose_name_plural': 'Token Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedbackDetailedRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique rating identifier (UUID).', primary_key=True, serialize=False)),
                ('accuracy_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How accurate was the AI feedback? (1=Very Inaccurate, 5=Very Accurate)')),
                ('helpfulness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How helpful was the feedback for learning? (1=Not Helpful, 5=Very Helpful)')),
                ('actionability_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='How actionable/specific were the suggestions? (1=Too Vague, 5=Very Specific)')),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Overall satisfaction with AI feedback (1=Very Dissatisfied, 5=Very Satisfied)')),
                ('has_false_positives', models.BooleanField(default=False, help_text='Did AI incorrectly flag issues that were actually correct?')),
                ('false_positive_details', models.TextField(blank=True, help_text='Details about false positives if any (what was incorrectly flagged?)', null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional textual comment about the AI feedback quality.', null=True)),
                ('rated_at', models.DateTimeField(auto_now_add=True, help_text='When this rating was submitted.')),
                ('report', models.ForeignKey(help_text='The user report being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback_ratings', to='cases.report')),
                ('user', models.ForeignKey(help_text='The user providing the rating.', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback Detailed Rating',
                'verbose_name_plural': 'AI Feedback Detailed Ratings',
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['rated_at'], name='detailed_rating_date_idx'), models.Index(fields=['accuracy_rating'], name='detailed_rating_accuracy_idx'), models.Index(fields=['helpfulness_rating'], name='detailed_rating_helpful_idx'), models.Index(fields=['actionability_rating'], name='detailed_rating_action_idx'), models.Index(fields=['has_false_positives'], name='detailed_rating_fp_idx')],
                'unique_together': {('report', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['version_number'], name='prompt_version_num_idx'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['is_active'], name='prompt_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['is_ab_test', 'ab_test_weight'], name='prompt_ab_test_idx'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['average_rating'], name='prompt_avg_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['created_at'], name='prompt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcache',
            index=models.Index(fields=['content_hash'], name='cache_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcache',
            index=models.Index(fields=['case', 'created_at'], name='cache_case_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcache',
            index=models.Index(fields=['expires_at'], name='cache_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcache',
            index=models.Index(fields=['hit_count'], name='cache_hits_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['created_at'], name='token_log_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['case', 'created_at'], name='token_log_case_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['was_cached'], name='token_log_cached_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['total_cost'], name='token_log_cost_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['prompt_version', 'created_at'], name='token_log_version_idx'),
        ),
    ]
