# Generated by Django 5.2 on 2025-05-02 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('resident', 'Resident'), ('fellow', 'Fellow'), ('attending', 'Attending'), ('admin', 'Administrator'), ('other', 'Other')], default='other', help_text="User's role in the institution", max_length=20)),
                ('institution', models.CharField(blank=True, help_text="User's institution or hospital affiliation", max_length=255)),
                ('country', models.CharField(blank=True, help_text="User's country", max_length=100)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', help_text='Approval status of the user account', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
