# backend/cases/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views # Import views from the current directory
from .views import AIReportFeedbackView, AIFeedbackRatingCreateView # UPDATED: Import AIFeedbackRatingCreateView

# Create a router and register our viewsets with it.
router = DefaultRouter()

# Register existing viewsets
router.register(r'admin/cases', views.AdminCaseViewSet, basename='admin-case')
router.register(r'cases', views.UserCaseViewSet, basename='user-case') # For regular users

router.register(r'admin/languages', views.LanguageViewSet, basename='language')
router.register(r'admin/templates', views.AdminMasterTemplateViewSet, basename='admin-master-template')
router.register(r'admin/case-templates', views.CaseTemplateViewSet, basename='admin-case-template')


# Define URL patterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),

    # Existing URL patterns
    path('reports/', views.ReportCreateView.as_view(), name='report-create'),
    path('my-reports/', views.MyReportsListView.as_view(), name='my-reports-list'),
    path('reports/<int:report_id>/ai-feedback/', AIReportFeedbackView.as_view(), name='report-ai-feedback'),

    # NEW URL PATTERN for creating AI Feedback Ratings
    path('ai-feedback-ratings/', AIFeedbackRatingCreateView.as_view(), name='ai-feedback-rating-create'),
]
