# cases/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views # Import views from the current directory

# Create a router and register our viewsets with it.
router = DefaultRouter()

# Register existing viewsets
router.register(r'admin/cases', views.AdminCaseViewSet, basename='admin-case')
router.register(r'cases', views.UserCaseViewSet, basename='user-case') # For regular users

router.register(r'admin/languages', views.LanguageViewSet, basename='language')
router.register(r'admin/templates', views.AdminMasterTemplateViewSet, basename='admin-master-template')

# <<< REGISTER NEW CaseTemplateViewSet HERE >>>
router.register(r'admin/case-templates', views.CaseTemplateViewSet, basename='admin-case-template')


# Define URL patterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),

    # Existing URL patterns (if any non-router patterns exist for cases)
    path('reports/', views.ReportCreateView.as_view(), name='report-create'),
    path('my-reports/', views.MyReportsListView.as_view(), name='my-reports-list'),
]